任何策略的本质都是在预测，一次预测包括用来预测的因子、被预测的变量、预测模型。预测是一个研究过程，包括不断调整
预测因子和预测模型，以获得最小的错误率

下面选定分钟bar的涨跌作为被预测变量，选定非常细粒度的数据的好处在于，可以快速的累积到足够多的样本数据。 缺点在于，越是高粒度
的数据，其规律越接近于随机游走，所以发现有效模型的概率越低。 关于预测因子，在高频交易的情况下，由于不需要考虑基本面的数据，所以
预测因子基本上也是过去的回报。为了预测一分钟的回报方向，选定过去1、3、5分钟的回报作为预测因子，模型上选用逻辑回归模型。预测因子
可以尝试下连续型和离散型

In [2]:
from se2.domain.time_series import *
from se2.domain.engine import *
from se2.domain.account import *
from se2.domain.common import *
import pandas as pd
import numpy as np
import scipy.stats

In [3]:
code = 'SPCE_STK_USD_SMART'
start = pd.Timestamp('2021-05-09 21:00:00', tz='Asia/Shanghai')
end = pd.Timestamp('2021-06-09 21:00:00', tz='Asia/Shanghai')
command = HistoryDataQueryCommand(start, end, [code])
ts_repo: TimeSeriesRepo = BeanContainer.getBean(TimeSeriesRepo)
ts: TimeSeries = ts_repo.find_one("ibMinBar")
MIN_BAR_DF: DataFrame = ts.history_data(command, from_local=True)
MIN_BAR_DF = MIN_BAR_DF.droplevel(level=1)
MIN_BAR_DF.head()

start_time   open   high    low  \
visible_time                                                               
2021-05-10 21:31:00+08:00 2021-05-10 21:30:00+08:00  19.58  19.59  19.32   
2021-05-10 21:32:00+08:00 2021-05-10 21:31:00+08:00  19.39  19.39  19.12   
2021-05-10 21:33:00+08:00 2021-05-10 21:32:00+08:00  19.15  19.35  19.07   
2021-05-10 21:34:00+08:00 2021-05-10 21:33:00+08:00  19.30  19.45  19.29   
2021-05-10 21:35:00+08:00 2021-05-10 21:34:00+08:00  19.37  19.38  19.27   

                           close  volume  
visible_time                              
2021-05-10 21:31:00+08:00  19.41    1624  
2021-05-10 21:32:00+08:00  19.16     387  
2021-05-10 21:33:00+08:00  19.30     432  
2021-05-10 21:34:00+08:00  19.41     299  
2021-05-10 21:35:00+08:00  19.27     190

In [36]:
# 构造训练集和验证集
df = MIN_BAR_DF[:'2021-05-11 21:00:00']
pre_ret1 = np.log(df['close'] / df['close'].shift(1))
pre_ret3 = np.log(df['close'] / df['close'].shift(3))
pre_ret5 = np.log(df['close'] / df['close'].shift(5))
next_ret1 = np.log(df['close'].shift(-1) / df['close'])
df = pd.DataFrame({"pre_ret1": pre_ret1, "pre_ret3": pre_ret3, "pre_ret5":pre_ret5, "next_ret1": next_ret1})
train_data = df.dropna()
train_data = train_data[train_data['next_ret1']!=0]
train_data.loc[train_data['next_ret1']>0, 'next_ret1'] = 1
train_data.loc[train_data['next_ret1']<0, 'next_ret1'] = -1

df = MIN_BAR_DF['2021-05-11 21:00:00':'2021-05-12 21:00:00']
pre_ret1 = np.log(df['close'] / df['close'].shift(1))
pre_ret3 = np.log(df['close'] / df['close'].shift(3))
pre_ret5 = np.log(df['close'] / df['close'].shift(5))
next_ret1 = np.log(df['close'].shift(-1) / df['close'])
df = pd.DataFrame({"pre_ret1": pre_ret1, "pre_ret3": pre_ret3, "pre_ret5":pre_ret5, "next_ret1": next_ret1})
test_data = df.dropna()
test_data = test_data[test_data['next_ret1']!=0]
test_data.loc[test_data['next_ret1']>0, 'next_ret1'] = 1
test_data.loc[test_data['next_ret1']<0, 'next_ret1'] = -1


In [42]:
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
X, y = load_iris(return_X_y=True)
clf = LogisticRegression(random_state=0).fit(X, y)
clf.predict(X[:2, :])

/Users/zhang/opt/miniconda3/envs/strategy-engine/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0, 0])

In [40]:
X[:2, :]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2]])

In [43]:
clf.predict_proba(X[:2, :])

array([[9.81802911e-01, 1.81970751e-02, 1.43580537e-08],
       [9.71729527e-01, 2.82704429e-02, 3.00353141e-08]])

In [44]:
clf.score(X, y)



0.9733333333333334

In [49]:
X = train_data[['pre_ret1','pre_ret3', 'pre_ret5']].values
y = train_data['next_ret1'].values
lr = LogisticRegression(random_state=0)
lr.fit(X, y)
X_t = test_data[['pre_ret1','pre_ret3', 'pre_ret5']].values
y_t = test_data['next_ret1'].values
lr.score(X_t, y_t)


0.45938375350140054

In [56]:
pd.concat([train_data['pre_ret5'], test_data['pre_ret5']]).describe()


count    696.000000
mean       0.000310
std        0.007099
min       -0.030332
25%       -0.003239
50%        0.000000
75%        0.003449
max        0.044397
Name: pre_ret5, dtype: float64

In [85]:
# 尝试使用离散的变量
new_train_data = train_data.copy()
new_train_data.loc[:,'pre_ret1'] = pd.qcut(new_train_data['pre_ret1'], 2, labels=[-1, 1])
new_train_data.loc[:,'pre_ret3'] = pd.qcut(new_train_data['pre_ret3'], 2, labels=[-1, 1])
new_train_data.loc[:,'pre_ret5'] = pd.qcut(new_train_data['pre_ret5'], 2, labels=[-1, 1])

new_test_data = test_data.copy()
new_test_data.loc[:,'pre_ret1'] = pd.qcut(new_test_data['pre_ret1'], 2, labels=[-1, 1])
new_test_data.loc[:,'pre_ret3'] = pd.qcut(new_test_data['pre_ret3'], 2, labels=[-1, 1])
new_test_data.loc[:,'pre_ret5'] = pd.qcut(new_test_data['pre_ret5'], 2, labels=[-1, 1])


In [86]:
X = new_train_data[['pre_ret1','pre_ret3', 'pre_ret5']].values
y = new_train_data['next_ret1'].values
lr = LogisticRegression(random_state=0)
lr.fit(X, y)
X_t = new_test_data[['pre_ret1','pre_ret3', 'pre_ret5']].values
y_t = new_test_data['next_ret1'].values
lr.score(X_t, y_t)

0.5210084033613446

In [95]:
MIN_BAR_DF[:'2021-05-11 21:00:00']

start_time   open   high    low  \
visible_time                                                               
2021-05-10 21:31:00+08:00 2021-05-10 21:30:00+08:00  19.58  19.59  19.32   
2021-05-10 21:32:00+08:00 2021-05-10 21:31:00+08:00  19.39  19.39  19.12   
2021-05-10 21:33:00+08:00 2021-05-10 21:32:00+08:00  19.15  19.35  19.07   
2021-05-10 21:34:00+08:00 2021-05-10 21:33:00+08:00  19.30  19.45  19.29   
2021-05-10 21:35:00+08:00 2021-05-10 21:34:00+08:00  19.37  19.38  19.27   
...                                             ...    ...    ...    ...   
2021-05-11 03:56:00+08:00 2021-05-11 03:55:00+08:00  17.92  17.97  17.91   
2021-05-11 03:57:00+08:00 2021-05-11 03:56:00+08:00  17.97  17.98  17.97   
2021-05-11 03:58:00+08:00 2021-05-11 03:57:00+08:00  17.98  17.98  17.90   
2021-05-11 03:59:00+08:00 2021-05-11 03:58:00+08:00  17.91  17.94  17.90   
2021-05-11 04:00:00+08:00 2021-05-11 03:59:00+08:00  17.94  17.98  17.93   

                           close  volume  
visible_time                              
2021-05-10 21:31:00+08:00  19.41    1624  
2021-05-10 21:32:00+08:00  19.16     387  
2021-05-10 21:33:00+08:00  19.30     432  
2021-05-10 21:34:00+08:00  19.41     299  
2021-05-10 21:35:00+08:00  19.27     190  
...                          ...     ...  
2021-05-11 03:56:00+08:00  17.96     875  
2021-05-11 03:57:00+08:00  17.98     481  
2021-05-11 03:58:00+08:00  17.91    1459  
2021-05-11 03:59:00+08:00  17.94     489  
2021-05-11 04:00:00+08:00  17.97    1426  

[390 rows x 6 columns]

In [116]:
from sklearn.svm import SVC

discretization_count = 2
labels = [-1, 1]

df = MIN_BAR_DF[:'2021-05-11 21:00:00']
pre_ret1 = np.log(df['close'] / df['close'].shift(1))
pre_ret3 = np.log(df['close'] / df['close'].shift(3))
pre_ret5 = np.log(df['close'] / df['close'].shift(5))
pre_ret10 = np.log(df['close'] / df['close'].shift(10))
pre_volume1 = df['volume']
next_ret1 = np.log(df['close'].shift(-1) / df['close'])
df = pd.DataFrame({"pre_ret1": pre_ret1, "pre_ret3": pre_ret3, "pre_ret5":pre_ret5,
                   "pre_volume1": pre_volume1,
                   "pre_ret10": pre_ret10,
                   "next_ret1": next_ret1})
train_data = df.dropna()
train_data = train_data[train_data['next_ret1']!=0]
train_data.loc[train_data['next_ret1']>0, 'next_ret1'] = 1
train_data.loc[train_data['next_ret1']<0, 'next_ret1'] = -1

df = MIN_BAR_DF['2021-05-11 21:00:00':'2021-05-12 21:00:00']
pre_ret1 = np.log(df['close'] / df['close'].shift(1))
pre_ret3 = np.log(df['close'] / df['close'].shift(3))
pre_ret5 = np.log(df['close'] / df['close'].shift(5))
pre_ret10 = np.log(df['close'] / df['close'].shift(10))
pre_volume1 = df['volume']
next_ret1 = np.log(df['close'].shift(-1) / df['close'])
df = pd.DataFrame({"pre_ret1": pre_ret1, "pre_ret3": pre_ret3, "pre_ret5":pre_ret5,
                   "pre_volume1": pre_volume1,
                   "pre_ret10": pre_ret10,
                   "next_ret1": next_ret1})
test_data = df.dropna()
test_data = test_data[test_data['next_ret1']!=0]
test_data.loc[test_data['next_ret1']>0, 'next_ret1'] = 1
test_data.loc[test_data['next_ret1']<0, 'next_ret1'] = -1


new_train_data = train_data.copy()
new_train_data.loc[:,'pre_ret1'] = pd.qcut(new_train_data['pre_ret1'], discretization_count, labels=labels)
new_train_data.loc[:,'pre_ret3'] = pd.qcut(new_train_data['pre_ret3'], discretization_count, labels=labels)
new_train_data.loc[:,'pre_ret5'] = pd.qcut(new_train_data['pre_ret5'], discretization_count, labels=labels)
new_train_data.loc[:,'pre_volume1'] = pd.qcut(new_train_data['pre_volume1'], discretization_count, labels=labels)
new_train_data.loc[:,'pre_ret10'] = pd.qcut(new_train_data['pre_ret10'], discretization_count, labels=labels)

new_test_data = test_data.copy()
new_test_data.loc[:,'pre_ret1'] = pd.qcut(new_test_data['pre_ret1'], discretization_count, labels=labels)
new_test_data.loc[:,'pre_ret3'] = pd.qcut(new_test_data['pre_ret3'], discretization_count, labels=labels)
new_test_data.loc[:,'pre_ret5'] = pd.qcut(new_test_data['pre_ret5'], discretization_count, labels=labels)
new_test_data.loc[:,'pre_volume1'] = pd.qcut(new_test_data['pre_volume1'], discretization_count, labels=labels)
new_test_data.loc[:,'pre_ret10'] = pd.qcut(new_test_data['pre_ret10'], discretization_count, labels=labels)


X = new_train_data[['pre_ret1','pre_ret3', 'pre_ret5']].values
y = new_train_data['next_ret1'].values
model = SVC()
model.fit(X, y)
print("train data score with svc:{}".format(model.score(X, y)))
model2 = LogisticRegression()
model2.fit(X, y)
print("train data score with lr:{}".format(model2.score(X, y)))
X_t = new_test_data[['pre_ret1','pre_ret3', 'pre_ret5']].values
y_t = new_test_data['next_ret1'].values
print("test data score with svc:{}".format(model.score(X_t, y_t)))
print("test data score with lr:{}".format(model2.score(X_t, y_t)))

train data score with svc:0.5688622754491018
train data score with lr:0.562874251497006
test data score with svc:0.547752808988764
test data score with lr:0.5224719101123596
